dist: xenial
language: python
python: 3.7
services:
  - docker
before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - docker login --username=_ --password=$HEROKU_AUTH_TOKEN registry.heroku.com
before_script: pip install docker-compose
script:
  - docker-compose run web python manage.py test -v 2
  - docker build -t web .
  - docker tag web registry.heroku.com/$HEROKU_APP_NAME/web

deploy:
  provider: script
  script:
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:release web --app $HEROKU_APP_NAME

      
      