version: "3"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - local-var.env
    depends_on:
      - db
  db:
    image: postgres:9.5-alpine
    environment:
      - POSTGRES_USER=sayaradz_user
      - POSTGRES_PASSWORD=sayaradz
      - POSTGRES_DB=sayaradz_db1
    
