"""
Django settings for sayaradz_api project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'tbgeak6_)g-+lknmhw!77)s-5_xk#zedysyerz!=9&mqehnc)r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'sayaradz',
    #-------------------------------social authentication--------------------------------#
    'social_django', #pour integrer la connection avec facebook et google
    'app1',          #pour tester le fonctionnement de social_django mannuellement
    'tests',         #pour tester le fonctionnement de social_django automatiquement
    #allauth
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    
    #------------------------------------------------------------------------------------#
   
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #---------------------------------ajouter 'OAuth'-------------------------------------#
    'social_django.middleware.SocialAuthExceptionMiddleware',  
    #-------------------------------------------------------------------------------------#
]

ROOT_URLCONF = 'sayaradz_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                 #-------------------- propre à 'OAuth'------------------------------------#
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
                #-------------------------------------------------------------------------#
            ],
        },
    },
]

WSGI_APPLICATION = 'sayaradz_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': "sayaradz_db",
            'USER': "sayaradz_user",
            'PASSWORD': "sayaradz",
            'HOST': "localhost",
            'PORT': "5432",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
      'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
#----------------------------AUTHENTICATION_BACKENDS--------------------------------------#
AUTHENTICATION_BACKENDS = (
    
    #allauth
        # Needed to login by username in Django admin, regardless of `allauth`
        'django.contrib.auth.backends.ModelBackend',

        # `allauth` specific authentication methods, such as login by e-mail
        'allauth.account.auth_backends.AuthenticationBackend',
    #Oauth
        'django.contrib.auth.backends.ModelBackend',
    #google Oauth
        'social_core.backends.google.GoogleOAuth2',
    #FB Oauth
        'social_core.backends.facebook.FacebookOAuth2',

)
#-----------------------------------------------------------------------------------------#

SITE_ID = 1
LOGIN_REDIRECT_URL ='/app1/'

#FaceBook Oauth
SOCIAL_AUTH_FACEBOOK_KEY = '2248858301999268'
SOCIAL_AUTH_FACEBOOK_SECRET = 'e991ccf631c58109e72236cced75395b'

#google Oauth
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY='292708405640-ejccn0gfordtblnkge1i6aqsrmnnc9jh.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET='CVy9Muvz8vkPaid8wAEToUP3'




