# Generated by Django 2.2.3 on 2019-09-13 11:05

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import sayaradz.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('notifications', '0006_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(blank=True, upload_to=sayaradz.models.get_upload_path3)),
                ('photo2', models.ImageField(blank=True, upload_to=sayaradz.models.get_upload_path3)),
                ('photo3', models.ImageField(blank=True, upload_to=sayaradz.models.get_upload_path3)),
                ('minPrice', models.FloatField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('year', models.CharField(max_length=4)),
                ('distance', models.CharField(max_length=10)),
                ('energy', models.CharField(max_length=20)),
                ('personsNumber', models.IntegerField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Automobilist',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.TextField()),
                ('telephone', models.CharField(max_length=15)),
                ('avatar', models.ImageField(blank=True, upload_to=sayaradz.models.get_upload_path4)),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AutomobilistNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.Notification')),
                ('notification_type', models.CharField(choices=[('OA', 'offer_accepted'), ('MC', 'model_changed'), ('VC', 'version_changed'), ('CV', 'command_valitaded')], default='OA', max_length=3)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
            bases=('notifications.notification',),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('numChassis', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('photo1', models.ImageField(blank=True, upload_to=sayaradz.models.get_upload_path2)),
                ('photo2', models.ImageField(blank=True, upload_to=sayaradz.models.get_upload_path2)),
                ('photo3', models.ImageField(blank=True, upload_to=sayaradz.models.get_upload_path2)),
                ('seller', models.TextField(default='')),
            ],
            options={
                'ordering': ['numChassis'],
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('total', models.FloatField()),
                ('isValidated', models.BooleanField(default=False)),
                ('reservationAmount', models.FloatField(null=True)),
                ('automobilist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayaradz.Automobilist')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayaradz.Car')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='LigneTarif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateBegin', models.DateField()),
                ('dateEnd', models.DateField()),
                ('price', models.FloatField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True)),
                ('nationality', models.CharField(blank=True, max_length=45)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayaradz.Manufacturer')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('code', 'manufacturer')},
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayaradz.MyModel')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('code', 'model')},
            },
        ),
        migrations.CreateModel(
            name='AutomobilistCommandValidatedNotification',
            fields=[
                ('automobilistnotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sayaradz.AutomobilistNotification')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
            bases=('sayaradz.automobilistnotification',),
        ),
        migrations.CreateModel(
            name='AutomobilistFollowedModelChangeNotification',
            fields=[
                ('automobilistnotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sayaradz.AutomobilistNotification')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
            bases=('sayaradz.automobilistnotification',),
        ),
        migrations.CreateModel(
            name='AutomobilistFollowedVersionChangeNotification',
            fields=[
                ('automobilistnotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sayaradz.AutomobilistNotification')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
            bases=('sayaradz.automobilistnotification',),
        ),
        migrations.CreateModel(
            name='NewCar',
            fields=[
                ('car_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sayaradz.Car')),
                ('isExisted', models.BooleanField(default=True)),
            ],
            bases=('sayaradz.car',),
        ),
        migrations.CreateModel(
            name='OccCar',
            fields=[
                ('car_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sayaradz.Car')),
            ],
            bases=('sayaradz.car',),
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayaradz.MyModel')),
                ('options', models.ManyToManyField(to='sayaradz.Option')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('code', 'model')},
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('offredPrice', models.FloatField()),
                ('isAccepted', models.BooleanField(default=False)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayaradz.Ad')),
                ('automobilist', models.ForeignKey(db_column='automobilist_id', on_delete=django.db.models.deletion.CASCADE, to='sayaradz.Automobilist')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ManufacturerUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.TextField()),
                ('telephone', models.CharField(max_length=15)),
                ('avatar', models.ImageField(blank=True, upload_to=sayaradz.models.get_upload_path1)),
                ('is_blocked', models.BooleanField(default=False)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayaradz.Manufacturer')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FollowedVersions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('automobilist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayaradz.Automobilist')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayaradz.Version')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='FollowedModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('automobilist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayaradz.Automobilist')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayaradz.MyModel')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayaradz.MyModel')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('code', 'model')},
            },
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.ForeignKey(db_column='color', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sayaradz.Color'),
        ),
        migrations.AddField(
            model_name='car',
            name='options',
            field=models.ManyToManyField(to='sayaradz.Option'),
        ),
        migrations.AddField(
            model_name='car',
            name='version',
            field=models.ForeignKey(db_column='version', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sayaradz.Version'),
        ),
        migrations.AddField(
            model_name='ad',
            name='automobilist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayaradz.Automobilist'),
        ),
        migrations.AddField(
            model_name='ad',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sayaradz.Manufacturer'),
        ),
        migrations.AddField(
            model_name='ad',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sayaradz.MyModel'),
        ),
        migrations.AddField(
            model_name='ad',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sayaradz.Version'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(max_length=25)),
                ('amount', models.FloatField()),
                ('automobilist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayaradz.Automobilist')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayaradz.Command')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('id', 'automobilist', 'command')},
            },
        ),
        migrations.CreateModel(
            name='LigneTarifVersion',
            fields=[
                ('lignetarif_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sayaradz.LigneTarif')),
                ('code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sayaradz.Version')),
            ],
            options={
                'ordering': ['code'],
            },
            bases=('sayaradz.lignetarif',),
        ),
        migrations.CreateModel(
            name='LigneTarifOption',
            fields=[
                ('lignetarif_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sayaradz.LigneTarif')),
                ('code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sayaradz.Option')),
            ],
            options={
                'ordering': ['code'],
            },
            bases=('sayaradz.lignetarif',),
        ),
        migrations.CreateModel(
            name='LigneTarifColor',
            fields=[
                ('lignetarif_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sayaradz.LigneTarif')),
                ('code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sayaradz.Color')),
            ],
            options={
                'ordering': ['code'],
            },
            bases=('sayaradz.lignetarif',),
        ),
        migrations.CreateModel(
            name='AutomobilistAcceptOfferNotification',
            fields=[
                ('automobilistnotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sayaradz.AutomobilistNotification')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayaradz.Offer')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
            bases=('sayaradz.automobilistnotification',),
        ),
        migrations.AlterUniqueTogether(
            name='ad',
            unique_together={('id', 'automobilist')},
        ),
    ]
