# Generated by Django 2.1.7 on 2019-03-26 21:11

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sayaradz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomobilistNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.Notification')),
                ('notification_type', models.CharField(choices=[('OA', 'offer_accepted'), ('MC', 'model_changed'), ('VC', 'version_changed'), ('CV', 'command_valitaded')], default='OA', max_length=1)),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('notifications.notification',),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='automobilist',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['numChassis']},
        ),
        migrations.AlterModelOptions(
            name='carseller',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='command',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='lignetarif',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='lignetarifcolor',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='lignetarifoption',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='lignetarifversion',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelManagers(
            name='automobilist',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='offredAmount',
            new_name='offredPrice',
        ),
        migrations.RemoveField(
            model_name='automobilist',
            name='familyName',
        ),
        migrations.RemoveField(
            model_name='automobilist',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='automobilist',
            name='id',
        ),
        migrations.RemoveField(
            model_name='automobilist',
            name='password',
        ),
        migrations.AddField(
            model_name='ad',
            name='description',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sayaradz.Manufacturer'),
        ),
        migrations.AddField(
            model_name='ad',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sayaradz.MyModel'),
        ),
        migrations.AddField(
            model_name='ad',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sayaradz.Version'),
        ),
        migrations.AddField(
            model_name='automobilist',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='automobilist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayaradz.Automobilist'),
        ),
        migrations.RemoveField(
            model_name='ad',
            name='car',
        ),
        migrations.AlterUniqueTogether(
            name='ad',
            unique_together={('id', 'automobilist')},
        ),
        migrations.AlterUniqueTogether(
            name='color',
            unique_together={('code', 'model')},
        ),
        migrations.AlterUniqueTogether(
            name='command',
            unique_together={('id', 'automobilist')},
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together={('code', 'model')},
        ),
        migrations.CreateModel(
            name='AutomobilistAcceptOfferNotification',
            fields=[
                ('automobilistnotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sayaradz.AutomobilistNotification')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('sayaradz.automobilistnotification',),
        ),
        migrations.CreateModel(
            name='AutomobilistCommandValidatedNotification',
            fields=[
                ('automobilistnotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sayaradz.AutomobilistNotification')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('sayaradz.automobilistnotification',),
        ),
        migrations.CreateModel(
            name='AutomobilistFollowedModelChangeNotification',
            fields=[
                ('automobilistnotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sayaradz.AutomobilistNotification')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('sayaradz.automobilistnotification',),
        ),
        migrations.CreateModel(
            name='AutomobilistFollowedVersionChangeNotification',
            fields=[
                ('automobilistnotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sayaradz.AutomobilistNotification')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('sayaradz.automobilistnotification',),
        ),
    ]
