# Generated by Django 2.2.3 on 2019-09-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayaradz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilist',
            name='facebook_id',
            field=models.CharField(default=11, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='automobilist',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='automobilist',
            name='profile_image',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
