# Generated by Django 2.1.7 on 2019-02-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayaradz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='make',
            name='nationality',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
