# Generated by Django 2.1.7 on 2019-03-27 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sayaradz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilistacceptoffernotification',
            name='offer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='sayaradz.Offer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='automobilistnotification',
            name='notification_type',
            field=models.CharField(choices=[('OA', 'offer_accepted'), ('MC', 'model_changed'), ('VC', 'version_changed'), ('CV', 'command_valitaded')], default='OA', max_length=3),
        ),
    ]
