# Generated by Django 2.1.7 on 2019-02-21 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sayaradz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MakeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('firstName', models.CharField(max_length=50)),
                ('familyName', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('telephone', models.CharField(max_length=15)),
                ('isBlocked', models.BooleanField(default=False)),
                ('make_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayaradz.Make')),
            ],
        ),
        
    ]
