# Generated by Django 2.2.3 on 2019-09-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayaradz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='automobilistacceptoffernotification',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='automobilistcommandvalidatednotification',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='automobilistfollowedmodelchangenotification',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='automobilistfollowedversionchangenotification',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='automobilistnotification',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='ad',
            name='energy',
            field=models.CharField(default=2017, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='personsNumber',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newcar',
            name='isExisted',
            field=models.BooleanField(default=False),
        ),
    ]
