# Generated by Django 2.1.7 on 2019-03-01 20:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
       
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sayaradz', '0002_auto_20190301_1629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Make',
            new_name='Manufacturer',
        ),
        migrations.RenameModel(
            old_name='MakeUser',
            new_name='ManufacturerUser',
        ),
        migrations.RemoveField(
            model_name='makeuser1',
            name='make',
        ),
        migrations.RemoveField(
            model_name='makeuser1',
            name='user',
        ),
        migrations.RenameField(
            model_name='manufactureruser',
            old_name='make',
            new_name='manufacturer',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='make',
            new_name='manufacturer',
        ),
        migrations.DeleteModel(
            name='MakeUser1',
        ),
    ]
