# Generated by Django 2.2.3 on 2019-09-13 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayaradz', '0002_auto_20190913_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilist',
            name='facebook_id',
        ),
    ]
