# Generated by Django 2.1.7 on 2019-02-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayaradz', '0002_auto_20190221_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makeuser',
            old_name='make_id',
            new_name='make',
        ),
    ]
