# Generated by Django 2.1.7 on 2019-04-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayaradz', '0002_auto_20190327_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='automobilistacceptoffernotification',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='automobilistcommandvalidatednotification',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='automobilistfollowedmodelchangenotification',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='automobilistfollowedversionchangenotification',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='automobilistnotification',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='command',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['date']},
        ),
        migrations.RenameField(
            model_name='command',
            old_name='isVlidated',
            new_name='isValidated',
        ),
        migrations.AddField(
            model_name='command',
            name='reservationAmount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='command',
            unique_together=set(),
        ),
    ]
