# Generated by Django 2.2.3 on 2019-09-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayaradz', '0002_auto_20190913_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcar',
            name='isExisted',
            field=models.BooleanField(default=True),
        ),
    ]
