# Generated by Django 2.2.3 on 2019-09-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayaradz', '0003_auto_20190913_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
