# Generated by Django 2.2.3 on 2019-09-13 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sayaradz', '0004_auto_20190913_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomobilistPostOfferNotification',
            fields=[
                ('automobilistnotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sayaradz.AutomobilistNotification')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayaradz.Offer')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
            bases=('sayaradz.automobilistnotification',),
        ),
    ]
