# Generated by Django 2.1.7 on 2019-03-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayaradz', '0004_auto_20190304_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufactureruser',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
