# Generated by Django 2.1.7 on 2019-06-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayaradz', '0003_auto_20190401_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='seller',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='CarSeller',
        ),
    ]
