# Generated by Django 2.1.7 on 2019-06-24 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sayaradz', '0004_auto_20190620_1600'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='car',
            name='seller',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='CarSeller',
        )
    ]
