# Generated by Django 2.1.7 on 2019-02-22 12:13

from django.db import migrations, models
import django.db.models.deletion
import sayaradz.models


class Migration(migrations.Migration):

    dependencies = [
        ('sayaradz', '0004_makeuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minPrice', models.FloatField()),
                ('date', models.DateField()),
                ('photo1', models.ImageField(blank=True, upload_to=sayaradz.models.get_upload_path3)),
                ('photo2', models.ImageField(blank=True, upload_to=sayaradz.models.get_upload_path3)),
                ('photo3', models.ImageField(blank=True, upload_to=sayaradz.models.get_upload_path3)),
            ],
        ),
        migrations.CreateModel(
            name='Automobilist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('familyName', models.CharField(max_length=50)),
                ('password', models.CharField(default='', max_length=100)),
                ('address', models.TextField()),
                ('telephone', models.CharField(max_length=15)),
                ('avatar', models.ImageField(blank=True, upload_to=sayaradz.models.get_upload_path4)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('numChassis', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('photo1', models.ImageField(blank=True, upload_to=sayaradz.models.get_upload_path2)),
                ('photo2', models.ImageField(blank=True, upload_to=sayaradz.models.get_upload_path2)),
                ('photo3', models.ImageField(blank=True, upload_to=sayaradz.models.get_upload_path2)),
            ],
        ),
        migrations.CreateModel(
            name='CarSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('isVlidated', models.BooleanField(default=False)),
                ('automobilist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayaradz.Automobilist')),
            ],
        ),
        migrations.CreateModel(
            name='LigneTarif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataBegin', models.DateField()),
                ('dataEnd', models.DateField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayaradz.Make')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('offredAmount', models.FloatField()),
                ('isAccepted', models.BooleanField(default=False)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayaradz.Ad')),
                ('automobilist', models.ForeignKey(db_column='automobilist_id', on_delete=django.db.models.deletion.CASCADE, to='sayaradz.Automobilist')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayaradz.Model')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='makeuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=sayaradz.models.get_upload_path1),
        ),
        migrations.CreateModel(
            name='LigneTarifColor',
            fields=[
                ('lignetarif_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sayaradz.LigneTarif')),
            ],
            bases=('sayaradz.lignetarif',),
        ),
        migrations.CreateModel(
            name='LigneTarifOption',
            fields=[
                ('lignetarif_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sayaradz.LigneTarif')),
            ],
            bases=('sayaradz.lignetarif',),
        ),
        migrations.CreateModel(
            name='LigneTarifVersion',
            fields=[
                ('lignetarif_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sayaradz.LigneTarif')),
                ('code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sayaradz.Version')),
            ],
            bases=('sayaradz.lignetarif',),
        ),
        migrations.CreateModel(
            name='NewCar',
            fields=[
                ('car_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sayaradz.Car')),
            ],
            bases=('sayaradz.car',),
        ),
        migrations.CreateModel(
            name='OccCar',
            fields=[
                ('car_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sayaradz.Car')),
            ],
            bases=('sayaradz.car',),
        ),
        migrations.AddField(
            model_name='option',
            name='versions',
            field=models.ManyToManyField(to='sayaradz.Version'),
        ),
        migrations.AddField(
            model_name='command',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayaradz.Car'),
        ),
        migrations.AddField(
            model_name='color',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayaradz.Model'),
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.ForeignKey(db_column='color', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sayaradz.Model'),
        ),
        migrations.AddField(
            model_name='car',
            name='options',
            field=models.ManyToManyField(to='sayaradz.Option'),
        ),
        migrations.AddField(
            model_name='car',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sayaradz.CarSeller'),
        ),
        migrations.AddField(
            model_name='car',
            name='version',
            field=models.ForeignKey(db_column='version', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sayaradz.Make'),
        ),
        migrations.AddField(
            model_name='automobilist',
            name='followedModels',
            field=models.ManyToManyField(to='sayaradz.Model'),
        ),
        migrations.AddField(
            model_name='automobilist',
            name='followedVersions',
            field=models.ManyToManyField(to='sayaradz.Version'),
        ),
        migrations.AddField(
            model_name='ad',
            name='automobilist',
            field=models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.CASCADE, to='sayaradz.Automobilist'),
        ),
        migrations.AddField(
            model_name='lignetarifoption',
            name='code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sayaradz.Option'),
        ),
        migrations.AddField(
            model_name='lignetarifcolor',
            name='code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sayaradz.Color'),
        ),
        migrations.AddField(
            model_name='ad',
            name='car',
            field=models.OneToOneField(db_column='car_numChassis', on_delete=django.db.models.deletion.CASCADE, to='sayaradz.OccCar'),
        ),
    ]
