<<<<<<< HEAD:sayaradz/migrations/0005_auto_20190624_2209.py
# Generated by Django 2.1.7 on 2019-06-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayaradz', '0004_auto_20190620_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='seller',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='CarSeller',
        ),
    ]
=======
# Generated by Django 2.1.7 on 2019-06-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayaradz', '0003_auto_20190401_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='seller',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='CarSeller',
        ),
    ]
>>>>>>> c745df1f36583b2cacbadd5dd1e4515f1c345463:sayaradz/migrations/0005_auto_20190624_2209.py
