# Generated by Django 2.1.7 on 2019-03-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayaradz', '0005_manufactureruser_is_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='versions',
        ),
        migrations.AddField(
            model_name='version',
            name='options',
            field=models.ManyToManyField(to='sayaradz.Option'),
        ),
    ]
