# Generated by Django 2.1.7 on 2019-03-05 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayaradz', '0006_auto_20190304_2306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mymodel',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['code']},
        ),
        migrations.AlterUniqueTogether(
            name='mymodel',
            unique_together={('code', 'manufacturer')},
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('code', 'model')},
        ),
    ]
