# Generated by Django 2.2.3 on 2019-09-14 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sayaradz', '0007_automobilistfollowedmodelchangenotification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilistfollowedversionchangenotification',
            name='version',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='sayaradz.Version'),
            preserve_default=False,
        ),
    ]
