# Generated by Django 2.2.3 on 2019-09-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayaradz', '0008_automobilistfollowedversionchangenotification_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilistnotification',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
