# Generated by Django 2.1.7 on 2019-03-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayaradz', '0008_auto_20190305_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='options',
            field=models.ManyToManyField(to='sayaradz.Option'),
        ),
    ]
