# Generated by Django 2.2.3 on 2019-09-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayaradz', '0009_automobilistnotification_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='photo1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ad',
            name='photo2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ad',
            name='photo3',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='automobilist',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo3',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='manufactureruser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
