# Generated by Django 2.1.7 on 2019-03-06 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayaradz', '0010_version_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='manufacturer',
        ),
    ]
