# Generated by Django 2.1.7 on 2019-03-06 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sayaradz', '0012_version_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='version',
            name='model',
            field=models.ForeignKey(default='0123456789', on_delete=django.db.models.deletion.CASCADE, to='sayaradz.MyModel'),
            preserve_default=False,
        ),
    ]
