# Generated by Django 2.1.7 on 2019-03-22 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sayaradz', '0013_auto_20190306_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='version',
            field=models.ForeignKey(db_column='version', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sayaradz.Version'),
        ),
    ]
