# Generated by Django 2.1.7 on 2019-03-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayaradz', '0015_auto_20190322_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignetarif',
            name='dateBegin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lignetarif',
            name='dateEnd',
            field=models.DateField(),
        ),
    ]
