# Generated by Django 2.1.7 on 2019-03-22 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayaradz', '0017_auto_20190322_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='price',
            new_name='total',
        ),
    ]
