# Generated by Django 2.1.7 on 2019-03-23 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sayaradz', '0018_auto_20190322_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='car',
        ),
        migrations.AddField(
            model_name='ad',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sayaradz.Manufacturer'),
        ),
        migrations.AddField(
            model_name='ad',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sayaradz.MyModel'),
        ),
        migrations.AddField(
            model_name='ad',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sayaradz.Version'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='automobilist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayaradz.Automobilist'),
        ),
    ]
