# Generated by Django 2.1.7 on 2019-03-24 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_indexes'),
        ('sayaradz', '0020_ad_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomobilistOfferAcceptNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.Notification')),
                ('adOwnerEmail', models.EmailField(max_length=255)),
                ('telephone', models.CharField(max_length=15)),
            ],
            bases=('notifications.notification',),
        ),
        migrations.CreateModel(
            name='ManufacturerUserCommandNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.Notification')),
            ],
            bases=('notifications.notification',),
        ),
        migrations.AddField(
            model_name='automobilist',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='automobilist',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
