# Generated by Django 2.1.7 on 2019-03-24 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayaradz', '0021_auto_20190324_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='offredAmount',
            new_name='offredPrice',
        ),
        migrations.RemoveField(
            model_name='automobilistofferacceptnotification',
            name='adOwnerEmail',
        ),
        migrations.RemoveField(
            model_name='automobilistofferacceptnotification',
            name='telephone',
        ),
    ]
