# Generated by Django 2.1.7 on 2019-03-24 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayaradz', '0022_auto_20190324_1408'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='automobilist',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='automobilistofferacceptnotification',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['numChassis']},
        ),
        migrations.AlterModelOptions(
            name='carseller',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='command',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='lignetarif',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='lignetarifcolor',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='lignetarifoption',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='lignetarifversion',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='manufacturerusercommandnotification',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['code']},
        ),
        migrations.AlterUniqueTogether(
            name='ad',
            unique_together={('id', 'automobilist')},
        ),
        migrations.AlterUniqueTogether(
            name='color',
            unique_together={('code', 'model')},
        ),
        migrations.AlterUniqueTogether(
            name='command',
            unique_together={('id', 'automobilist')},
        ),
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together={('id', 'automobilist')},
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together={('code', 'model')},
        ),
    ]
