# Generated by Django 2.1.7 on 2019-03-24 14:55

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sayaradz', '0023_auto_20190324_1529'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='automobilist',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='automobilist',
            name='email',
        ),
        migrations.RemoveField(
            model_name='automobilist',
            name='familyName',
        ),
        migrations.RemoveField(
            model_name='automobilist',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='automobilist',
            name='id',
        ),
        migrations.RemoveField(
            model_name='automobilist',
            name='password',
        ),
        migrations.AddField(
            model_name='automobilist',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together=set(),
        ),
    ]
