# Generated by Django 2.1.7 on 2019-03-22 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayaradz', '0014_auto_20190322_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lignetarif',
            old_name='dataBegin',
            new_name='dateBegin',
        ),
        migrations.RenameField(
            model_name='lignetarif',
            old_name='dataEnd',
            new_name='dateEnd',
        ),
    ]
