# Generated by Django 2.1.7 on 2019-03-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayaradz', '0024_auto_20190324_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilistofferacceptnotification',
            name='notification_ptr',
        ),
        migrations.RemoveField(
            model_name='manufacturerusercommandnotification',
            name='notification_ptr',
        ),
        migrations.DeleteModel(
            name='AutomobilistOfferAcceptNotification',
        ),
        migrations.DeleteModel(
            name='ManufacturerUserCommandNotification',
        ),
    ]
