# Generated by Django 2.1.7 on 2019-03-26 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_indexes'),
        ('sayaradz', '0025_auto_20190326_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomobilistNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.Notification')),
                ('notification_type', models.CharField(choices=[('OA', 'offer_accepted'), ('MC', 'model_changed'), ('VC', 'version_changed'), ('CV', 'command_valitaded')], default='OA', max_length=1)),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('notifications.notification',),
        ),
        migrations.CreateModel(
            name='ManufacturerUserCommandNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.Notification')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('notifications.notification',),
        ),
        migrations.CreateModel(
            name='AutomobilistAcceptOfferNotification',
            fields=[
                ('automobilistnotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sayaradz.AutomobilistNotification')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('sayaradz.automobilistnotification',),
        ),
        migrations.CreateModel(
            name='AutomobilistCommandValidatedNotification',
            fields=[
                ('automobilistnotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sayaradz.AutomobilistNotification')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('sayaradz.automobilistnotification',),
        ),
        migrations.CreateModel(
            name='AutomobilistFollowedModelChangeNotification',
            fields=[
                ('automobilistnotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sayaradz.AutomobilistNotification')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('sayaradz.automobilistnotification',),
        ),
        migrations.CreateModel(
            name='AutomobilistFollowedVersionChangeNotification',
            fields=[
                ('automobilistnotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sayaradz.AutomobilistNotification')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('sayaradz.automobilistnotification',),
        ),
    ]
