# Generated by Django 2.1.7 on 2019-03-26 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayaradz', '0026_automobilistacceptoffernotification_automobilistcommandvalidatednotification_automobilistfollowedmod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturerusercommandnotification',
            name='notification_ptr',
        ),
        migrations.DeleteModel(
            name='ManufacturerUserCommandNotification',
        ),
    ]
